### PR TITLE
Add Sky: Children of the Light soundtrack (take two) 

### PR DESCRIPTION
**Pull request by phthallo**
**Youtube Video:** https://www.youtube.com/watch?v=87etrUp83Yc

**Reasoning:** Ticks all the boxes; has chill nature sounds along with relaxing ambience with vibes to fit any studying atmosphere (soundtracks accompany each area in the game; there's a rainy forest, a library/vault of knowledge, luscious prairies, underwater reefs, etc)
It's the soundtrack of the 'cozy' indie game [Sky: Children of the Light](https://en.wikipedia.org/wiki/Sky_(video_game)).

If you'd like recommendations, my favourites are Waltzing in the Rain, Geysers and Gullies and As The Tide Turns! :)

-- 
sorry about that, it should now be up to date! thanks for your work on the plugin!

### CODE REVIEW

**Review by andrewmcgivery — APPROVED** [review]
Thanks so much!

**Comment by error451** [comment]
Thanks a lot! I'm glad to see relation between sky cotl and obsidian, my 2 favorite digital spaces where I like to spend my time <3 I didn't even know how much i wanted this until i saw it was in the options 🤭

**Comment by phthallo** [comment]
@error451 No worries! Sky's one of my favourite chill games too :) 

Yeah, it might be a region-based/connectivity issue - particularly if you're on a school Wi-Fi network or something like that. Where are you located?

**Comment by error451** [comment]
yes definitely i have an issue with embed link https://www.youtube.com/embed/87etrUp83Yc (Video unavailable - Watch on YouTube)
I'm on my home network, Europe, but not a part of EU.
When i use proxy, sometimes i can play that embed link.
Also i tested it on geopeeker website and other similar sites, it worked for Australia and Canada, but didn't work for Ireland, Brazil, Singapore, Japan, ...
The issue only appear for the [embed link](https://www.youtube.com/embed/87etrUp83Yc) from this message, the [regular link](https://www.youtube.com/watch?v=87etrUp83Yc) from request message always works.
we should probably use a different video or repost this (as unlisted) if copyright and sky game terms allow it (I don't understand it enough to say), but without any limitations for embed links.

**Pull request merged**
